add_defines("_GNU_SOURCE=1")

target("termux")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("termux.c")
    add_deps("termux_api")
target_end()

target("brightness")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("brightness.c")
    add_deps("termux_api")
target_end()

target("clipboard")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("clipboard.c")
    add_deps("termux_api")
target_end()

target("dialog_confirm")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_confirm.c")
    add_deps("termux_api")
target_end()

target("dialog_checkbox")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_checkbox.c")
    add_deps("termux_api")
target_end()

target("dialog_counter")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_counter.c")
    add_deps("termux_api")
target_end()

target("dialog_date")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_date.c")
    add_deps("termux_api")
target_end()

target("dialog_radio")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_radio.c")
    add_deps("termux_api")
target_end()

target("dialog_sheet")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_sheet.c")
    add_deps("termux_api")
target_end()

target("dialog_spinner")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_spinner.c")
    add_deps("termux_api")
target_end()

target("dialog_speech")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_speech.c")
    add_deps("termux_api")
target_end()

target("dialog_text")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_text.c")
    add_deps("termux_api")
target_end()

target("dialog_time")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("dialog_time.c")
    add_deps("termux_api")
target_end()

target("fingerprint")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("fingerprint.c")
    add_deps("termux_api")
target_end()

target("sensor")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("sensor.c")
    add_deps("termux_api")
target_end()

target("toast")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("toast.c")
    add_deps("termux_api")
target_end()

target("torch")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("torch.c")
    add_deps("termux_api")
target_end()

target("vibrate")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("vibrate.c")
    add_deps("termux_api")
target_end()

target("volume")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("volume.c")
    add_deps("termux_api")
target_end()
